# This is a basic workflow to help you get started with Actions

name: test-network

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ autorun, dev ]
  pull_request:
    branches: [ autorun, dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: 
          sudo apt install -y zsh jq
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Install Fabric Test Network
        run: |
          cd ~
          curl -sSL https://bit.ly/2ysbOFE | bash -s -- 2.3.3 1.5.2
      - name: Run Tests
        run: |
          export PATH=~/fabric-samples/bin:$PATH
          cd ~/fabric-samples/test-network
          wget https://raw.githubusercontent.com/kward/shunit2/d0a57ff2e6c5d8fbd27f9bebd1896037ce628f9d/shunit2
          $GITHUB_WORKSPACE/src/test/shell/makeNewSaleTest.sh
